version: '3.8'

services:
  app:
    build: .
    image: pokemon-api
    ports:
      - '3000:3000'
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: 'redis:6-alpine'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
